### ISSUE TITLE
初回スクリプト実行時に hyper config file is not exist エラー

### ISSUE THREAD

**Issue by badmintoncryer** [Shimpei-GANGAN/setup-hyper-pokemon#5]
```brew install hyper```実行後にsetup.shを実行しても
```sh
------- hyper config file is not exist -------
```
エラーになってしまいました。

```brew install hyper```だけでは~/.hyper.jsが作成されなかったのが原因のようです。
スクリプト実行前に以下コマンドを実行し解消できましたが、正しいアプローチかは不明です。
```sh
 hyper i hyper-pokemon
```

**Comment by Shimpei-GANGAN** [comment]
@badmintoncryer 

エラー報告頂きありがとうございます！
本エラー内容について私の方で検証を行います。

`hyper-pokemon`の本家がかなり古いリポジトリのため、ライブラリ起因か、hyper terminal起因かについても合わせて調査を行います。

**Comment by badmintoncryer** [comment]
すみません！環境情報だけ補足しておきます
OS: Ventura 13.5.2
M1 Mac
